version: '3.8'

volumes:
  profile-fluid_document-data: {}
  profile-fluid_db-data: {}

services:
  apache-php:
    build:
      target: dev
    extra_hosts:
      - host.docker.internal:host-gateway
    labels:
      - traefik.enable=true
      - traefik.docker.network=indocker-app-network
      - traefik.http.routers.fluid-profile-router.rule=Host(`fluid-profile.indocker.app`)
      - traefik.http.routers.fluid-profile-router.service=fluid-profile-service
      - traefik.http.services.fluid-profile-service.loadbalancer.server.port=80
    networks:
      - indocker-app-network

  mariadb:
    container_name: profile-fluid_mariadb
    build:
      context: ./mariadb
    command: [
      'mysqld',
      '--collation-server=utf8_general_ci',
      '--character-set-server=utf8',
      '--log-bin=mysql-bin',
      '--binlog-format=row',
      '--binlog-row-image=full'
    ]
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '*'
    ports:
      - ${DB_EXTERNAL_PORT}:3306
    volumes:
      - 'profile-fluid_db-data:/var/lib/mysql'
      - './logs/mysql:/var/log/mysql'
    networks:
      - profile-fluid

  minio:
    container_name: profile-fluid_minio
    image: bitnami/minio:2023.5.4-debian-11-r1
    environment:
      MINIO_ROOT_USER: ${STORAGE_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${STORAGE_SECRET_ACCESS_KEY}
    volumes:
      - profile-fluid_document-data:/data
    ports:
      - ${MINIO_EXTERNAL_PORT}:9001
    networks:
      - profile-fluid
         #ipv4_address: 172.25.0.3

networks:
  profile-fluid:
    name: profile-fluid
  indocker-app-network:
    external: true
