version: '3.8'

volumes:
  profile-fluid_data: {}

services:
  apache-php:
    container_name: profile-fluid_apache-php
    restart: unless-stopped
    build:
      context: ./apache-php
      dockerfile: apache-php.Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - APACHE_STATUS_USER=${APACHE_STATUS_USER:-test}
        - APACHE_STATUS_PASSWORD=${APACHE_STATUS_PASSWORD:-test}
    volumes:
      - ./apache-php/htdocs:/var/www/html
      - ./logs/apache:/var/log/apache2
    environment:
      - CONTAINER_ROLE=http
    networks:
      - profile-fluid
    security_opt: [no-new-privileges:true]
    labels:
      logging: "promtail"
      service: "apache-php"
      site: "profile.fluid-line.ru"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  prometheus-apache-exporter:
    image: bitnami/apache-exporter:latest
    container_name: profile-fluid_prometheus-apache-exporter
    depends_on:
      - apache-php
    command:
      - --log.level=info
      - --insecure
      - --telemetry.address=0.0.0.0:9117
      - --telemetry.endpoint=/metrics
      - --scrape_uri=http://${APACHE_STATUS_USER:-test}:${APACHE_STATUS_PASSWORD:-test}@apache-php/server-status/?auto
    networks:
      - profile-fluid
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  promtail:
    container_name: profile-fluid_promtail
    restart: unless-stopped
    image: grafana/promtail:2.8.2
    volumes:
      - ./promtail/config.yml:/etc/promtail/docker-config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    command: [
      '-config.file=/etc/promtail/docker-config.yml',
      '-config.expand-env=true',
#      '--dry-run', # Для тестирования
    ]
    environment:
      LOKI_CLIENT_PUSH_ADDR: ${LOKI_CLIENT_PUSH_ADDR:-http://localhost/loki/api/push}
      LOKI_CLIENT_BASIC_AUTH_USERNAME: ${LOKI_CLIENT_BASIC_AUTH_USERNAME:-user}
      LOKI_CLIENT_BASIC_AUTH_PASSWORD: ${LOKI_CLIENT_BASIC_AUTH_PASSWORD:-password}
    networks:
      - 'profile-fluid'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      org.label-schema.group: "monitoring"

networks:
  profile-fluid:
    name: profile-fluid