version: '3.8'

volumes:
  profile-fluid_data: {}

services:
  apache-php:
    container_name: profile-fluid_apache-php
    restart: always
    build:
      context: ./apache-php
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - APACHE_STATUS_USER=${APACHE_STATUS_USER:-test}
        - APACHE_STATUS_PASSWORD=${APACHE_STATUS_PASSWORD:-test}
      target: ${ENV}
    volumes:
      - ./apache-php/htdocs:/var/www/html
      - ./logs/apache:/var/log/apache2
    networks:
      - profile-fluid
    security_opt: [no-new-privileges:true]

  prometheus-apache-exporter:
    image: bitnami/apache-exporter:latest
    container_name: profile-fluid_prometheus-apache-exporter
    depends_on:
      - apache-php
    command:
      - --log.level=info
      - --insecure
      - --telemetry.address=0.0.0.0:9117
      - --telemetry.endpoint=/metrics
      - --scrape_uri=http://${APACHE_STATUS_USER:-test}:${APACHE_STATUS_PASSWORD:-test}@apache-php/server-status/?auto
    networks:
      - profile-fluid

  mariadb:
    container_name: profile-fluid_mariadb
    restart: always
    build:
      context: ./mariadb
    command: [
      'mysqld',
      '--collation-server=utf8_general_ci', 
      '--character-set-server=utf8'
    ]
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '*'
    ports:
      - ${DB_EXTERNAL_PORT}:3306
    volumes:
      - 'profile-fluid_data:/var/lib/mysql'
      - './logs/mysql:/var/log/mysql'
    networks:
      - profile-fluid

networks:
  profile-fluid:
    name: profile-fluid