version: '3.8'

volumes:
  profile-fluid_data: {}

services:
  apache-php:
    container_name: profile-fluid_apache-php
    restart: unless-stopped
    build:
      context: ./apache-php
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - APACHE_STATUS_USER=${APACHE_STATUS_USER:-test}
        - APACHE_STATUS_PASSWORD=${APACHE_STATUS_PASSWORD:-test}
    volumes:
      - ./apache-php/htdocs:/var/www/html
      - ./logs/apache:/var/log/apache2
    networks:
      - profile-fluid
    security_opt: [no-new-privileges:true]

  prometheus-apache-exporter:
    image: bitnami/apache-exporter:latest
    container_name: profile-fluid_prometheus-apache-exporter
    depends_on:
      - apache-php
    command:
      - --log.level=info
      - --insecure
      - --telemetry.address=0.0.0.0:9117
      - --telemetry.endpoint=/metrics
      - --scrape_uri=http://${APACHE_STATUS_USER:-test}:${APACHE_STATUS_PASSWORD:-test}@apache-php/server-status/?auto
    networks:
      - profile-fluid

networks:
  profile-fluid:
    name: profile-fluid