server:
  disable: true
  log_level: warn

positions:
  filename: /etc/promtail/positions.yaml

clients:
  - url: ${LOKI_CLIENT_PUSH_ADDR}
    batchwait: 20s
    batchsize: 5242880
    basic_auth:
      username: ${LOKI_CLIENT_BASIC_AUTH_USERNAME}
      password: ${LOKI_CLIENT_BASIC_AUTH_PASSWORD}

scrape_configs:
  - job_name: apache      
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: [ "logging=promtail", "service=apache-php", "site=profile.fluid-line.ru" ]
    pipeline_stages:
      - json:
          expressions:
            level_name: level_name
      - drop:
          source: "level_name"
      - static_labels:
          service: "apache"
      - regex:
          expression: ^(?P<ip>\\S+) - - \\[(?P<timestamp>[\\w:/]+\\s[+\\-]\\d{4})\\] \\"(?P<action>\\S+)\\s?(?P<path>\\S+)?\\s?(?P<protocol>\\S+)?\" (?P<status_code>\\d{3}|-) (?P<size>[^ ]*)
      - labels:
          action:
          status_code:
      - timestamp:
          source: timestamp
          format: "02/Jan/2006:15:04:05 -0700"
          location: "Europe/Moscow"
    relabel_configs:
      - source_labels: [ '__meta_docker_container_id' ]
        target_label: 'container_id'
      - source_labels: [ '__meta_docker_container_name' ]
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: [ '__meta_docker_container_log_stream' ]
        target_label: 'logstream'
      - source_labels: [ '__meta_docker_container_label_logging_jobname' ]
        target_label: 'job'
      - source_labels: [ '__meta_docker_container_label_site' ]
        target_label: 'site'
        
  - job_name: php
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: [ "logging=promtail", "service=apache-php", "site=profile.fluid-line.ru" ]
    pipeline_stages:
      - static_labels:
          service: "php"
      - json:
          expressions:
            level_name: level_name
            channel: channel
            timestamp: datetime
      - labels:
          level_name:
          channel:
      - match:
          selector: '{level_name=~""}'
          action: drop
      - timestamp:
          source: timestamp
          format: "RFC3339Nano"
    relabel_configs:
      - source_labels: [ '__meta_docker_container_id' ]
        target_label: 'container_id'
      - source_labels: [ '__meta_docker_container_name' ]
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: [ '__meta_docker_container_log_stream' ]
        target_label: 'logstream'
      - source_labels: [ '__meta_docker_container_label_logging_jobname' ]
        target_label: 'job'
      - source_labels: [ '__meta_docker_container_label_site' ]
        target_label: 'site'
